version: "3"
services:
  vendor-portal:
    image: thakurkumarrahul/selenium
    environment:
      - BROWSER
      - TEST_SUITE=vendor-portal.xml
      - HUB_HOST=hub
      - THREAD_COUNT=3
    volumes:
      - ./output/vendor-portal:/home/selenium/test-output

  flight-reservation:
    image: thakurkumarrahul/selenium
    environment:
      - BROWSER
      - TEST_SUITE=flight-reservation.xml
      - HUB_HOST=hub
      - THREAD_COUNT=4
    volumes:
      - ./output/flight-reservation:/home/selenium/test-output